[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline"

[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true
  skip = false

[[headers]]
  for = "/assets/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
      X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.js"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = "*", Country = [], Language = []}

[[plugins]]
  package = "@netlify/plugin-lighthouse"
    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9

[dev]
  framework = "vite"
  targetPort = 5173
